In [1]:
import pandas as pd

The "illinois_data_df.csv" file is too large to push to the github repo, so it has been removed from the folder. This is how the cleaning was done though.

In [2]:
file1 = "illinois_data_df.csv"
file2 = "zip_code_database.csv"

ill_df = pd.read_csv(file1, dtype=str)
zip_df = pd.read_csv(file2, dtype=str)

In [3]:
ill_df = ill_df.replace(to_replace='Zip Code: ', value='', regex=True)

In [4]:
ill_df

,Unnamed: 0,Worksheet Filter,Measure Display,Number of Records,Avg Sale To List,Avg Sale To List Mom,Avg Sale To List Yoy,City,Homes Sold,Homes Sold Mom,...,property_type_id,Region,Region Type,region_type_id,Sold Above List,Sold Above List Mom,Sold Above List Yoy,State,State Code,Table Id
0,206,Value,NaN,1,0.889830508,NaN,NaN,NaN,1.0,NaN,...,3,"Iroquois County, IL",County,5,0.0,NaN,NaN,Illinois,IL,749
1,236,Value,NaN,1,0.935897436,25.0%,NaN,NaN,1.0,-66.7%,...,4,"Kankakee County, IL",County,5,0.0,0.0,NaN,Illinois,IL,757
2,244,Value,NaN,1,0.975862931,2.1%,0.2%,Oak Park,27.0,8.0%,...,6,"Oak Park, IL",Place/City,6,0.222222222,0.10222222199999999,0.016339869,Illinois,IL,14204
3,658,Value,NaN,1,0.968423247,-0.5%,-1.8%,Morton Grove,49.0,53.1%,...,6,"Morton Grove, IL",Place/City,6,0.06122449,-0.25127551,-0.37877551,Illinois,IL,13031
4,706,Value,NaN,1,0.949149392,0.4%,-0.4%,NaN,52.0,18.2%,...,-1,"Grundy County, IL",County,5,0.153846154,0.04020979,0.07051282099999999,Illinois,IL,743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440858,9256473,Value,NaN,1,0.976113352,0.1%,0.9%,NaN,25.0,13.6%,...,13,60565,Zip Code,2,0.08,-0.010909091000000001,-0.031111111,Illinois,IL,26071
440859,9256474,Value,NaN,1,0.94621132,-1.3%,-3.0%,NaN,4.0,33.3%,...,13,60416,Zip Code,2,0.0,0.0,-0.333333333,Illinois,IL,25946
440860,9256475,Value,NaN,1,0.983663537,0.8%,0.9%,NaN,30.0,-18.9%,...,13,60142,Zip Code,2,0.333333333,0.144144144,0.141025641,Illinois,IL,25868
440861,9256476,Value,NaN,1,0.951903863,-2.3%,NaN,NaN,4.0,0.0%,...,13,60706,Zip Code,2,0.0,-0.25,NaN,Illinois,IL,26167
440862,9256477,Value,NaN,1,0.963310615,0.1%,0.0%,NaN,12.0,9.1%,...,13,60173,Zip Code,2,0.083333333,-0.007575758,-0.05952381,Illinois,IL,25895

In [5]:
main_df = ill_df.set_index('Region').join(zip_df.set_index('zip'), how='left')

In [6]:
main_df['county'].unique()

array(['Lake County', 'Cook County', 'McHenry County', 'DuPage County',
       'Kane County', 'DeKalb County', 'Will County', 'Grundy County',
       'Kendall County', 'LaSalle County', 'Kankakee County',
       'Boone County', 'Winnebago County', 'Champaign County',
       'Madison County', 'Macoupin County', 'Jersey County',
       'St. Clair County', 'Clinton County', 'Monroe County',
       'Bond County', 'Randolph County', nan], dtype=object)

In [7]:
cc_df = main_df.loc[main_df['county']=='Cook County']

In [8]:
cc_df

,Unnamed: 0,Worksheet Filter,Measure Display,Number of Records,Avg Sale To List,Avg Sale To List Mom,Avg Sale To List Yoy,City,Homes Sold,Homes Sold Mom,...,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population_2015
60004,590316,Value,NaN,1,0.9508431190000001,-0.5%,1.7%,NaN,178.0,-0.6%,...,NaN,IL,Cook County,America/Chicago,"847,224",NaN,US,42.09,-87.98,52270
60004,609960,Value,NaN,1,0.96155453,-0.1%,-0.6%,NaN,161.0,-11.5%,...,NaN,IL,Cook County,America/Chicago,"847,224",NaN,US,42.09,-87.98,52270
60004,650614,Value,NaN,1,0.9464752609999999,0.6%,NaN,NaN,84.0,-14.3%,...,NaN,IL,Cook County,America/Chicago,"847,224",NaN,US,42.09,-87.98,52270
60004,664744,Value,NaN,1,0.966033038,0.4%,1.4%,NaN,233.0,14.8%,...,NaN,IL,Cook County,America/Chicago,"847,224",NaN,US,42.09,-87.98,52270
60004,704578,Value,NaN,1,0.928583114,0.0%,-4.3%,NaN,26.0,-10.3%,...,NaN,IL,Cook County,America/Chicago,"847,224",NaN,US,42.09,-87.98,52270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,7577298,Value,NaN,1,0.922883764,-0.8%,16.4%,NaN,5.0,-16.7%,...,NaN,IL,Cook County,America/Chicago,"773,872,708",NaN,US,41.64,-87.63,21840
60827,7625300,Value,NaN,1,0.921389947,-0.7%,-19.2%,NaN,4.0,-20.0%,...,NaN,IL,Cook County,America/Chicago,"773,872,708",NaN,US,41.64,-87.63,21840
60827,8988071,Value,NaN,1,0.9444117879999999,0.0%,1.6%,NaN,42.0,-22.2%,...,NaN,IL,Cook County,America/Chicago,"773,872,708",NaN,US,41.64,-87.63,21840
60827,9122246,Value,NaN,1,0.93712485,0.7%,11.3%,NaN,2.0,-33.3%,...,NaN,IL,Cook County,America/Chicago,"773,872,708",NaN,US,41.64,-87.63,21840
60827,9189638,Value,NaN,1,0.98781128,1.2%,-0.7%,NaN,42.0,-10.6%,...,NaN,IL,Cook County,America/Chicago,"773,872,708",NaN,US,41.64,-87.63,21840

In [9]:
list(cc_df.columns)

['Unnamed: 0',
 'Worksheet Filter',
 'Measure Display',
 'Number of Records',
 'Avg Sale To List',
 'Avg Sale To List Mom',
 'Avg Sale To List Yoy',
 'City',
 'Homes Sold',
 'Homes Sold Mom',
 'Homes Sold Yoy',
 'Inventory',
 'Inventory Mom',
 'Inventory Yoy',
 'Seasonally Adjusted',
 'last_updated',
 'Median Dom',
 'Median Dom Mom',
 'Median Dom Yoy',
 'Median List Ppsf',
 'Median List Ppsf Mom',
 'Median List Ppsf Yoy',
 'Median List Price',
 'Median List Price Mom',
 'Median List Price Yoy',
 'Median Ppsf',
 'Median Ppsf Mom',
 'Median Ppsf Yoy',
 'Median Sale Price',
 'Median Sale Price Mom',
 'Median Sale Price Yoy',
 'months_of_supply',
 'months_of_supply_mom',
 'months_of_supply_yoy',
 'New Listings',
 'New Listings Mom',
 'New Listings Yoy',
 'off_market_in_two_weeks',
 'off_market_in_two_weeks_mom',
 'off_market_in_two_weeks_yoy',
 'parent_metro_region',
 'parent_metro_region_metro_code',
 'pending_sales',
 'pending_sales_mom',
 'pending_sales_yoy',
 'Period Begin',
 'Period Duration',
 'Period End',
 'Price Drops',
 'Price Drops Mom',
 'Price Drops Yoy',
 'Property Type',
 'property_type_id',
 'Region Type',
 'region_type_id',
 'Sold Above List',
 'Sold Above List Mom',
 'Sold Above List Yoy',
 'State',
 'State Code',
 'Table Id',
 'type',
 'decommissioned',
 'primary_city',
 'acceptable_cities',
 'unacceptable_cities',
 'state',
 'county',
 'timezone',
 'area_codes',
 'world_region',
 'country',
 'latitude',
 'longitude',
 'irs_estimated_population_2015']

In [10]:
cc_df = cc_df.drop(columns=['Unnamed: 0', 'Worksheet Filter', 'Measure Display', 'Number of Records', 'City', 'Seasonally Adjusted',
                   'last_updated', 'months_of_supply', 'months_of_supply_mom', 'months_of_supply_yoy', 'Period Duration',
                   'Period End', 'Region Type', 'region_type_id', 'Table Id', 'type', 'decommissioned', 'acceptable_cities',
                   'unacceptable_cities', 'state', 'timezone', 'area_codes', 'world_region', 'country', 'latitude', 'longitude',
                           'Price Drops', 'Price Drops Mom', 'Price Drops Yoy', 'parent_metro_region_metro_code', 'parent_metro_region'])

In [11]:
cc_df

,Avg Sale To List,Avg Sale To List Mom,Avg Sale To List Yoy,Homes Sold,Homes Sold Mom,Homes Sold Yoy,Inventory,Inventory Mom,Inventory Yoy,Median Dom,...,Property Type,property_type_id,Sold Above List,Sold Above List Mom,Sold Above List Yoy,State,State Code,primary_city,county,irs_estimated_population_2015
60004,0.9508431190000001,-0.5%,1.7%,178.0,-0.6%,33.8%,205.0,-7.2%,-28.8%,78.5,...,All Residential,-1,0.08426966300000001,0.00047078,-0.05858748,Illinois,IL,Arlington Heights,Cook County,52270
60004,0.96155453,-0.1%,-0.6%,161.0,-11.5%,-11.5%,242.0,-15.7%,-4.3%,62.0,...,All Residential,-1,0.086956522,-0.011944577,-0.022933587999999998,Illinois,IL,Arlington Heights,Cook County,52270
60004,0.9464752609999999,0.6%,NaN,84.0,-14.3%,NaN,304.0,-3.2%,NaN,98.0,...,All Residential,-1,0.14285714300000002,0.030612245,NaN,Illinois,IL,Arlington Heights,Cook County,52270
60004,0.966033038,0.4%,1.4%,233.0,14.8%,31.6%,194.0,2.6%,-29.5%,42.0,...,All Residential,-1,0.19742489300000002,0.020084991,0.10702941199999999,Illinois,IL,Arlington Heights,Cook County,52270
60004,0.928583114,0.0%,-4.3%,26.0,-10.3%,4.0%,28.0,7.7%,55.6%,54.0,...,Condo/Co-op,3,0.076923077,-0.026525199,-0.083076923,Illinois,IL,Arlington Heights,Cook County,52270
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60827,0.922883764,-0.8%,16.4%,5.0,-16.7%,150.0%,9.0,-25.0%,12.5%,158.0,...,Townhouse,13,0.2,0.033333333,0.2,Illinois,IL,Riverdale,Cook County,21840
60827,0.921389947,-0.7%,-19.2%,4.0,-20.0%,100.0%,3.0,-25.0%,NaN,31.0,...,Townhouse,13,0.25,0.05,-0.25,Illinois,IL,Riverdale,Cook County,21840
60827,0.9444117879999999,0.0%,1.6%,42.0,-22.2%,-6.7%,82.0,-2.4%,13.9%,60.0,...,All Residential,-1,0.19047619,-0.068783069,-0.076190476,Illinois,IL,Riverdale,Cook County,21840
60827,0.93712485,0.7%,11.3%,2.0,-33.3%,-33.3%,7.0,-22.2%,-12.5%,166.0,...,Multi-Family (2-4 Unit),4,0.0,0.0,-0.333333333,Illinois,IL,Riverdale,Cook County,21840
60827,0.98781128,1.2%,-0.7%,42.0,-10.6%,23.5%,68.0,15.3%,6.3%,35.0,...,Single Family Residential,6,0.380952381,0.061803445,-0.047619048,Illinois,IL,Riverdale,Cook County,21840

In [12]:
list(cc_df.columns)

['Avg Sale To List',
 'Avg Sale To List Mom',
 'Avg Sale To List Yoy',
 'Homes Sold',
 'Homes Sold Mom',
 'Homes Sold Yoy',
 'Inventory',
 'Inventory Mom',
 'Inventory Yoy',
 'Median Dom',
 'Median Dom Mom',
 'Median Dom Yoy',
 'Median List Ppsf',
 'Median List Ppsf Mom',
 'Median List Ppsf Yoy',
 'Median List Price',
 'Median List Price Mom',
 'Median List Price Yoy',
 'Median Ppsf',
 'Median Ppsf Mom',
 'Median Ppsf Yoy',
 'Median Sale Price',
 'Median Sale Price Mom',
 'Median Sale Price Yoy',
 'New Listings',
 'New Listings Mom',
 'New Listings Yoy',
 'off_market_in_two_weeks',
 'off_market_in_two_weeks_mom',
 'off_market_in_two_weeks_yoy',
 'pending_sales',
 'pending_sales_mom',
 'pending_sales_yoy',
 'Period Begin',
 'Property Type',
 'property_type_id',
 'Sold Above List',
 'Sold Above List Mom',
 'Sold Above List Yoy',
 'State',
 'State Code',
 'primary_city',
 'county',
 'irs_estimated_population_2015']

In [15]:
cc_df.to_csv('cook_county_data.csv')